### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by mvrozanti** [ncornette/Python-Markdown-Editor#16]
After installing requirements with `pip3 install --user -r requirements.txt` I still get `ModuleNotFoundError: No module named 'mdx_pymdownx'`

**Comment by ramlaxman** [comment]
Ya. For me,
ModuleNotFoundError: No module named 'pymdownx.github'

**Comment by mvrozanti** [comment]
@ramlaxman 
I think you're looking for this
https://github.com/iamcco/markdown-preview.vim

**Comment by ncornette** [comment]
fixed !
