### ISSUE TITLE
Issue with (current version of ) pymdown-extensions 8.x

### ISSUE THREAD

**Issue by diegoasua** [ncornette/Python-Markdown-Editor#25]
Installing with pip the installation goes fine, but when launching the editor from command line it throws the following error:

```
ModuleNotFoundError: No module named 'pymdownx.extrarawhtml'
```

Uninstalling ```pymdown-extensions``` and reinstalling a previous version e.g. ```pymdown-extensions==7.0``` solved the issue for me. This happens because the requirement for installation is ```pymdown-extensions>=2.0``` but can quickly be fixed by specifying exact version.

**Comment by ncornette** [comment]
Fixed in version 1.0.6 (thank you for comment)
