### ISSUE TITLE
don't work , just the web and only on folder install

### ISSUE THREAD

**Issue by catafest** [ncornette/Python-Markdown-Editor#26]
not working with the simple command like in documentation:
_Launch editor without input file for testing :
$ markdown_edit_
I need to go to the folder where is install and run it, that shows the web editor: http://localhost:8222/
``` ... site-packages/markdown_editor/web_edit.py ```
see the install I used: 
```
[mythcat@desk ~]$ pip install markdown-editor
...
[mythcat@desk ~]$ markdown_edit
bash: markdown_edit: command not found
```

**Comment by ncornette** [comment]
You need to open a new terminal (or close your session) for the path to be updated
