### ISSUE TITLE
localhost port

### ISSUE THREAD

**Issue by baoboa** [ncornette/Python-Markdown-Editor#4]
First, i say it's a very nice little python code and when we compare it to haroopad and its never ending list of dependencies it's nice to have something light. 

#### my question:

* it did fail at first for me  because i was already using another SimpleHTTPServer instance , is it possible to add an option to define the default port or to chose one at random ?

**Comment by ncornette** [comment]
Thank you for your feedback, default port is now 8222, and can be overriden by the -p or --port argument.

Remember you can still use the Terminal Edit mode with -t or --terminal, which doesn't involve a web server.

**Comment by baoboa** [comment]
noted , thanks
